name: "Terraform"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  DAY_OF_WEEK: Monday
  ARM_CLIENT_ID: 'e54c489c-92a4-4b25-a005-1710958dda46'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: 'ec18dca1-0751-4307-bbac-6150896ac498'
  ARM_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
jobs:
  dev-env:
    name: "Dev Enviornment"
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Run code
      #   run: |
      #     printf ${{ secrets.BACKEND_TFVARS }}

      - name: Output current branch name & date
      # To use latest action, specify "release-master" instead of "v0.0.2"
        uses: satackey/action-js-inline@v0.0.2
        id: getdata
        env:
          TFVARS: ${{secrets.BACKEND_TFVARS}}
        with:
          # Edit the following line to install packages required to run your script.
          required-packages: axios
          script: |
            const core = require('@actions/core')
            const axios = require('axios')
            console.log(` result is ${process.env.TFVARS}`);

      - name: Deploy Terraform Dev Enviornment
        uses: ./actions/deployTerraform
        # uses: mhassaninmsft/SampleRepo1@v1
        with:
          who-to-greet: 'Mohamed'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFVARS_CONTENT: ${{ secrets.BACKEND_TFVARS }}