name: "Terraform"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  ARM_CLIENT_ID: 'e54c489c-92a4-4b25-a005-1710958dda46'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: 'ec18dca1-0751-4307-bbac-6150896ac498'
  ARM_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
jobs:
  dev-env:
    name: "Dev Enviornment"
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Terraform Enviornment
        uses: ./actions/deployTerraform
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFVARS_CONTENT: ${{ secrets.BACKEND_TFVARS }}
          ENVIRONMENT: dev

  test-env:
    name: "Test Enviornment"
    runs-on: ubuntu-latest
    needs: [dev-env]
    environment: test
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Terraform Enviornment
        uses: ./actions/deployTerraform
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFVARS_CONTENT: ${{ secrets.BACKEND_TFVARS }}
          ENVIRONMENT: test

  prod-env:
    name: "Prod Enviornment"
    runs-on: ubuntu-latest
    needs: [test-env]
    environment: prod
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Terraform Enviornment
        uses: ./actions/deployTerraform
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFVARS_CONTENT: ${{ secrets.BACKEND_TFVARS }}
          ENVIRONMENT: prod