name: "Terraform"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  DAY_OF_WEEK: Monday
  ARM_CLIENT_ID: 'e54c489c-92a4-4b25-a005-1710958dda46'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: 'ec18dca1-0751-4307-bbac-6150896ac498'
  ARM_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Terraform Dev Enviornment
        uses: ./actions/greet
        # uses: mhassaninmsft/SampleRepo1@v1
        with:
          who-to-greet: 'Mohamed'